//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class audience_loading
    {
        public int timetableId { get; set; }
        public string discipline_name { get; set; }
        public string room { get; set; }
        public string lesson_number { get; set; }
        public string week_name { get; set; }
        public int week_account { get; set; }
        public string teacher_name { get; set; }
        public string department_name { get; set; }
        public string position_name { get; set; }
        public string rank_name { get; set; }
        public int group_id { get; set; }
        public Nullable<int> group_count_people { get; set; }
        public string specialty_name { get; set; }
        public string faculty_name { get; set; }
        public string train_type_name { get; set; }
    }
}
