//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class timetable_dbEntities : DbContext
    {
        public timetable_dbEntities()
            : base("name=timetable_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audiences> audiences { get; set; }
        public virtual DbSet<changedescription> changedescription { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<dir_lessons> dir_lessons { get; set; }
        public virtual DbSet<disciplines> disciplines { get; set; }
        public virtual DbSet<faculties> faculties { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<positions> positions { get; set; }
        public virtual DbSet<ranks> ranks { get; set; }
        public virtual DbSet<specialties> specialties { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<timetable> timetable { get; set; }
        public virtual DbSet<timetable_changes> timetable_changes { get; set; }
        public virtual DbSet<train_types> train_types { get; set; }
        public virtual DbSet<audience_loading> audience_loading { get; set; }
        public virtual DbSet<audience_msg> audience_msg { get; set; }
        public virtual DbSet<lesson_msg> lesson_msg { get; set; }
        public virtual DbSet<teachers_hours> teachers_hours { get; set; }
        public virtual DbSet<timetable_changesview> timetable_changesview { get; set; }
    }
}
