//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplines : ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disciplines()
        {
            this.timetable_changes = new HashSet<timetable_changes>();
            this.timetable = new HashSet<timetable>();
        }
    
        public int discipline_id { get; set; }
        public string discipline_name { get; set; }
        public int department_id { get; set; }
    
        public virtual departments departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable_changes> timetable_changes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable> timetable { get; set; }

        public object Clone()
        {
            return new disciplines
            {
                department_id = this.department_id,
                discipline_name = this.discipline_name,
                discipline_id = this.department_id,
                departments = this.departments,
                timetable = this.timetable
            };
        }

    }
}
