//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public groups()
        {
            this.timetable = new HashSet<timetable>();
        }
    
        public int group_id { get; set; }
        public int count_people { get; set; }
        public int id_specialty { get; set; }
        public int id_trainform { get; set; }
        public int id_faculty { get; set; }
    
        public virtual faculties faculties { get; set; }
        public virtual specialties specialties { get; set; }
        public virtual train_types train_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable> timetable { get; set; }

        public object Clone()
        {
            return new groups
            {
                group_id = this.group_id,
                count_people = this.count_people,
                id_faculty = this.id_faculty,
                id_specialty = this.id_specialty,
                id_trainform = this.id_trainform,
                faculties = this.faculties,
                specialties = this.specialties,
                train_types = this.train_types,
                timetable = this.timetable
            };
        }

    }
}
