//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialties : ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public specialties()
        {
            this.groups = new HashSet<groups>();
        }
    
        public int specialty_id { get; set; }
        public string specialty_name { get; set; }
        public int faculty_id { get; set; }
    
        public virtual faculties faculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groups> groups { get; set; }

        public object Clone()
        {
            return new specialties
            {
                specialty_id = this.specialty_id,
                specialty_name = this.specialty_name,
                faculty_id = this.faculty_id,
                faculties = this.faculties,
                groups = this.groups
            };
        }
    }
}
