//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers_hours
    {
        public string teacherName { get; set; }
        public string teacher_departmentName { get; set; }
        public string teacher_positionName { get; set; }
        public string teacher_rankName { get; set; }
        public Nullable<decimal> teacher_workhours { get; set; }
        public Nullable<decimal> teacher_workyears { get; set; }
        public int teacherId { get; set; }
    }
}
