//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers : ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teachers()
        {
            this.timetable_changes = new HashSet<timetable_changes>();
            this.timetable = new HashSet<timetable>();
        }
    
        public int teacher_id { get; set; }
        public string name { get; set; }
        public int position_id { get; set; }
        public int rank_id { get; set; }
        public int department_id { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual positions positions { get; set; }
        public virtual ranks ranks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable_changes> timetable_changes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable> timetable { get; set; }

        public object Clone()
        {
            return new teachers
            {
                teacher_id = this.teacher_id,
                departments = this.departments,
                department_id = this.department_id,
                timetable = this.timetable,
                ranks = this.ranks,
                rank_id = this.rank_id,
                name = this.name,
                positions = this.positions,
                position_id = this.position_id
            };
        }

    }
}
