//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timetable()
        {
            this.timetable_changes = new HashSet<timetable_changes>();
        }
    
        public int timetable_id { get; set; }
        public int group_id { get; set; }
        public int room { get; set; }
        public int teacher_id { get; set; }
        public int discipline_id { get; set; }
        public int lesson_number { get; set; }
        public System.DateTime date { get; set; }
        public bool evenweek { get; set; }
    
        public virtual audiences audiences { get; set; }
        public virtual dir_lessons dir_lessons { get; set; }
        public virtual disciplines disciplines { get; set; }
        public virtual groups groups { get; set; }
        public virtual teachers teachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable_changes> timetable_changes { get; set; }

        public object Clone()
        {
            return new timetable
            {
                timetable_id = this.timetable_id,
                group_id = this.group_id,
                room = this.room,
                teacher_id = this.teacher_id,
                discipline_id = this.discipline_id,
                lesson_number = this.lesson_number,
                date = this.date,
                evenweek = this.evenweek,

                audiences = this.audiences,
                dir_lessons = this.dir_lessons,
                disciplines = this.disciplines,
                groups = this.groups,
                teachers = this.teachers

            };
        }

    }
}
