//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class timetable_dbEntities2 : DbContext
    {
        public timetable_dbEntities2()
            : base("name=timetable_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<faculties> faculties { get; set; }
        public virtual DbSet<specialties> specialties { get; set; }
        public virtual DbSet<train_types> train_types { get; set; }
        public virtual DbSet<audiences> audiences { get; set; }
        public virtual DbSet<days_week> days_week { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<dir_lessons> dir_lessons { get; set; }
        public virtual DbSet<disciplines> disciplines { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<positions> positions { get; set; }
        public virtual DbSet<ranks> ranks { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<timetable> timetable { get; set; }
        public virtual DbSet<audience_loading> audience_loading { get; set; }
        public virtual DbSet<teachers_hours> teachers_hours { get; set; }
    }
}
