//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable_changes
    {
        public int timetablechange_id { get; set; }
        public int timetable_id { get; set; }
        public int changedescription_id { get; set; }
        public int room { get; set; }
        public int teacher_id { get; set; }
        public int discipline_id { get; set; }
        public int lesson_number { get; set; }
        public System.DateTime date { get; set; }
        public bool evenweek { get; set; }
    
        public virtual audiences audiences { get; set; }
        public virtual changedescription changedescription { get; set; }
        public virtual dir_lessons dir_lessons { get; set; }
        public virtual disciplines disciplines { get; set; }
        public virtual teachers teachers { get; set; }
        public virtual timetable timetable { get; set; }
    }
}
