//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int timetable_id { get; set; }
        public int group_id { get; set; }
        public int room { get; set; }
        public int teacher_id { get; set; }
        public int discipline_id { get; set; }
        public int lesson_number { get; set; }
        public int weekday_id { get; set; }
        public int week_account { get; set; }
    
        public virtual audiences audiences { get; set; }
        public virtual days_week days_week { get; set; }
        public virtual dir_lessons dir_lessons { get; set; }
        public virtual disciplines disciplines { get; set; }
        public virtual groups groups { get; set; }
        public virtual teachers teachers { get; set; }

        public object Clone()
        {
            return new timetable
            {
                timetable_id = this.timetable_id,
                group_id = this.group_id,
                room = this.room,
                teacher_id = this.teacher_id,
                discipline_id = this.discipline_id,
                lesson_number = this.lesson_number,
                weekday_id = this.weekday_id,
                week_account = this.week_account,

                audiences = this.audiences,
                days_week = this.days_week,
                dir_lessons = this.dir_lessons,
                disciplines = this.disciplines,
                groups = this.groups,
                teachers = this.teachers

            };
        }

    }
}
