//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable_changesview
    {
        public int timetable_id { get; set; }
        public string description { get; set; }
        public string room { get; set; }
        public string teacher_name { get; set; }
        public int teacher_id { get; set; }
        public string discipline_name { get; set; }
        public string lesson_number { get; set; }
        public System.DateTime date { get; set; }
        public string evenweek { get; set; }
        public int group_id { get; set; }
        public bool completed { get; set; }
    }
}
